const shopTypes = {
     // CATEGORIES
     GET_CATEGORIES_ASYNC_START: "shop/GET_CATEGORIES_ASYNC_START",
     GET_CATEGORIES_ASYNC_SUCCESS: "shop/GET_CATEGORIES_ASYNC_SUCCESS",
     GET_CATEGORIES_ASYNC_FAILURE: "shop/GET_CATEGORIES_ASYNC_FAILURE",
 
     // SHOP DATA
     GET_SHOP_DATA_ASYNC_START: "shop/GET_SHOP_DATA_ASYNC_START",
     GET_SHOP_DATA_ASYNC_SUCCESS: "shop/GET_SHOP_DATA_ASYNC_SUCCESS",
     GET_SHOP_DATA_ASYNC_FAILURE: "shop/GET_SHOP_DATA_ASYNC_FAILURE",
 
    ADD_TO_FAVORITES: "shop/ADD_TO_FAVORITES",
    DECREASE_FAVORITES_ITEM_COUNT: "shop/DECREASE_FAVORITES_ITEM_COUNT",
    DELETE_FROM_FAVORITES: "shop/DELETE_FROM_FAVORITES",
    SET_MODAL_STATE: "shop/SET_MODAL_STATE",
};

export default shopTypes;