const types = {
    CLEAR_USER_DATA: "auth/CLEAR_USER_DATA",
    USER_SIGNIN_ASYNC_START: "auth/USER_SIGNIN_ASYNC_START",
    USER_SIGNIN_ASYNC_SUCCESS: "auth/USER_SIGNIN_ASYNC_SUCCESS",
    USER_SIGNIN_ASYNC_FAILURE: "auth/USER_SIGNIN_ASYNC_FAILURE",
};

export default types;